import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/assets/font_awesome_pro/css/all.css";
import LoadingAnimation from "@/components/LoadingAnimation";
import { TERMINAL_LINES } from "@/constants/animation.constant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingAnimation
          maxLines={TERMINAL_LINES.length}
          terminalLines={TERMINAL_LINES}
        />
        {children}
      </body>
    </html>
  );
};
